baseurl = "https://herenow.pw/"
languageCode = "en-us"
title = "herenow"
copyright = "No rights reserved."
disqusShortname = "herenowpw"

[author]
    name = "Leo Oshiro"

[blackfriday]
  plainIDAnchors = true

